### ISSUE TITLE
Policy for regional iTunes links?

### ISSUE THREAD

**Issue by scribblemaniac** [dkhamsing/open-source-ios-apps#321]
Should iTunes links that only work in some countries (ex. US only apps) be included? This question branches into another question depending on the answer. If we do refuse such links, then how will someone in a country where the app is allowed know that there are regional restrictions? If we accept these links, then how can we (contributors) verify the authenticity of the links without being from one of the allowed regions?

---

## TODO

- [x] update contributing
- [x] ~~update pull request template~~
- [x] update convert script to include globe icon 🌐
- [x] update readme keys to
- [x] remove `us/`

```
🔶 Swift projects

Projects that are not in English have a flag
🇨🇳 Project is in Chinese
🇪🇸 Project is in Spanish, etc

🌐 App is only available for a certain region

 100+ Stars: 🔥
 200+ Stars: 🔥🔥
 500+ Stars: 🔥🔥🔥
1000+ Stars: 🔥🔥🔥🔥
2000+ Stars: 🔥🔥🔥🔥🔥
```

**Comment by dkhamsing** [comment]
Good question
The original spirit was to allow any country .. I think if the link loads in the browser (desktop), we should be ok?? What do you think

**Comment by scribblemaniac** [comment]
I think that is acceptable, however I think we should add some indication that the app has region restrictions. That could either be something in the description (ex `Some app description (US only)`) or another icon and a restricted tag (ex. ⛔ or 🚫 )

**Comment by dkhamsing** [comment]
Hm can we do this based on the itunes url

- https://itunes.apple.com/app/gorillas/id302275459 👍 
- https://itunes.apple.com/us/app/molecules/id284943090 👍 
- https://itunes.apple.com/gb/app/closebox-find-closest-postbox/id556364813 ⛔  or 🚫  or ❗

**Comment by dkhamsing** [comment]
Well we should just have the indicator if not us (first two cases)

**Comment by scribblemaniac** [comment]
I feel that might be a bit overkill.

If you are set on having an indicator for international/global apps, here are a few other options I think might also work: 🌍 🌎 🌏 🌐

**Comment by dkhamsing** [comment]
I like this one 🌐

**Comment by dkhamsing** [comment]
```

```
🔶 Swift projects

Projects that are not in English have a flag
🇨🇳 Project is in Chinese
🇪🇸 Project is in Spanish, etc

🌐 App is only available for a certain region

 100+ Stars: 🔥
 200+ Stars: 🔥🔥
 500+ Stars: 🔥🔥🔥
1000+ Stars: 🔥🔥🔥🔥
2000+ Stars: 🔥🔥🔥🔥🔥
```
```

**Comment by scribblemaniac** [comment]
I like it 👍 

What should the tag within content.json be?

**Comment by dkhamsing** [comment]
I'd like to do this by inspecting the itunes url.. ok?

**Comment by scribblemaniac** [comment]
Ok. We'll have to add something to contributing.md about cleaning iTunes links since you can have something like this:
- https://itunes.apple.com/gb/app/molecules/id284943090
- https://itunes.apple.com/us/app/molecules/id284943090

Which would probably fool your url inspection.

**Comment by dkhamsing** [comment]
Verifying the itunes url should be part of the pull request

**Comment by dkhamsing** [comment]
Adding some TODOs at the top

**Comment by dkhamsing** [comment]
Hmm only one app falls into this category, Closebox 😅

**Comment by dkhamsing** [comment]
Gonna be closing this for now because it's not too much of an issue, will only update a couple of things

- [x] update contributing
- [x] remove `us/`

we can revisit adding 🌐  to the readme later
